// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckoutController from "./checkout_controller"
application.register("checkout", CheckoutController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FooterController from "./footer_controller"
application.register("footer", FooterController)

import HomeController from "./home_controller"
application.register("home", HomeController)
